# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/tulir/gomuks
%global goipath         github.com/tulir/gomuks
Version:                0.2.4

%gometa

%global common_description %{expand:
A terminal based Matrix client written in Go.}

%global golicenses      LICENSE lib/ansimage/LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A terminal based Matrix client written in Go

# Upstream license specification: AGPL-3.0-only and MPL-2.0
License:        AGPLv3 and MPLv2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/gomuks %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE lib/ansimage/LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Thu Mar 10 2022 Elagost <me@elagost.com> - 0.2.4-1
- Initial package
